
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8snginxappsotkust
  namespace: fluxcdtutorial
spec:
  interval: 30s
  path: ./deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8snginxappsot

